export enum screens {
  APP = 'APP',
  REGISTRATION = 'REGISTRATION',
  HOME = 'HOME',
  MEDIA = 'MEDIA',
  NO_INTERNET = 'NO_INTERNET',
  SEARCH = 'SEARCH',
  PROFILE = 'PROFILE',
  STAFF_IN = 'STAFF_IN',
  FILM_IN = 'FILM_IN',
  CREATE_PROFILE = 'CREATE_PROFILE',
  AUTH = 'AUTH',
}
